### ISSUE TITLE
no movie found

### ISSUE THREAD

**Issue by bedge** [mattsson/movies-ratings-alfred#1]
I must be doing something wrong as othe IMDB alfred plugins have the same problem for me:
![screen shot 2016-04-03 at 6 49 36 pm](https://cloud.githubusercontent.com/assets/499317/14236603/02b1a412-f9cd-11e5-978c-3c648e0ce636.png)

Not sure if this is a valid invocation. I'm not an alfred whiz. I just use it.

> %> python "./Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.7992B63D-CD02-48AE-AD2E-6C9345AD52E8/movieratings.py" "die hard"
> <?xml version="1.0" encoding="utf-8"?>
> <items><item valid="no"><title>Nothing was found.</title><subtitle /></item></items>22:30:40 workflow.py:2320 WARNING  Can't save last version: workflow has no version
> 22:30:40 workflow.py:2176 DEBUG    Workflow finished in 0.765 seconds.

**Comment by KevinBatdorf** [comment]
Same thing for me

**Comment by dwhdrbdhs** [comment]
The API of omdbapi.com has updated.
So the code needs update too.
movieratings.py  line  22 should be:

``` python
if 'Response' in moviesData and moviesData['Response'] == "False":
```

**Comment by mattsson** [comment]
The plugin works again now. I also fixed the script being blocked by non-finished requests. Sorry about not responding sooner! :-S
