### ISSUE TITLE
Rottentomatoes API

### ISSUE THREAD

**Issue by inspiredearth** [mattsson/movies-ratings-alfred#5]
There are no results coming up for RT. I suspect this is due to recent changes in their API policies. I am not sure what the exact policies are, but I have my own API key.

Is there a way to use my own API key?
Are there plans to, or even the means to, update the workflow to use an API key that works within the new TOS for RT API?

**Comment by mattsson** [comment]
I do not use the RT API, I use the OMDb API and they changed their response data structure which is why the RT score is always N/A. Thanks for creating an issue, I'll add a fix. :)

**Comment by mattsson** [comment]
Done: https://github.com/mattsson/movies-ratings-alfred/releases/tag/1.0.3

**Comment by inspiredearth** [comment]
Great. Thank you.
