### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ghost** [mattsson/movies-ratings-alfred#6]
![screen shot 2017-05-26 at 16 51 12](https://cloud.githubusercontent.com/assets/5307981/26495181/910412d6-4233-11e7-8c92-dc4a7d003d6e.png)

**Comment by mattsson** [comment]
Thanks for letting me know. Will take a look at this ASAP.

**Comment by mattsson** [comment]
Fixed in new release: https://github.com/mattsson/movies-ratings-alfred/releases/tag/1.0.4
