### ISSUE TITLE
Please enter more than 1 character

### ISSUE THREAD

**Issue by sublistic** [mattsson/movies-ratings-alfred#7]
Downloaded latest version today - v1.0.4

First the output says "Please enter more than 1 character" regardless of how many characters I've entered.

![screenshot 2017-07-11 09 08 52](https://user-images.githubusercontent.com/771477/28040411-d3cc1b2c-6619-11e7-92f0-ba80a101071b.png)

Then after about 15 seconds it returns the error message, but with no further details.

![screenshot 2017-07-11 09 09 15](https://user-images.githubusercontent.com/771477/28040435-ecdead64-6619-11e7-8f98-2a64a1b430cd.png)

Alfred 3.4, OSX 10.12.5

**Comment by mattsson** [comment]
I'll take a look as soon as I can, some time next week. Thanks.

**Comment by mattsson** [comment]
Does this version fix the problem?

[Movie Ratings.alfredworkflow.zip](https://github.com/mattsson/movies-ratings-alfred/files/1173333/Movie.Ratings.alfredworkflow.zip)

**Comment by sublistic** [comment]
Yeah, that works great, thanks!

<img width="593" alt="screenshot 2017-07-26 21 41 17" src="https://user-images.githubusercontent.com/771477/28614886-66556c86-724b-11e7-897e-2017de4c027b.png">

Awesome work, and thanks for a great workflow!
